version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: npm test -- --watch=false
      - run:
          name: Run end-to-end tests
          command: npx cypress run

workflows:
  version: 2
  test:
    jobs